#define forn(i, b) for(int i = 0; i < int(b); ++i)
#define forr(i, b) for(int i = int(b)-1; i >= 0; i--)
#define rep(i, a, b) for(int i = int(a); i < int(b); ++i)
#define rev(i, a, b) for(int i = int(b); i >= int(a); i--)
#define trav(ref, ds) for(auto &ref: ds)