name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/hydrogen" 

      - name: Navigate to website folder
        working-directory: ./website
        run: echo "Now in the website directory."

      - name: Install dependencies
        working-directory: ./website
        run: npm install

      - name: Build Docusaurus
        working-directory: ./website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          publish_branch: gh-pages

      - name: Notify success
        run: echo "Deployment successful on GitHub Pages."
